### ISSUE TITLE
Accordion: Alle öffnen/Alle schließen 

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-elements#1]
Optionalen "Schalter" ermöglichen, mit dem alle Accordions geöffnet und geschlossen werden können.
Ggf. auch über Ansteuerung über URL ermöglichen, die man dann via Suche auch ansteuern könnte um das Problem zu lösen, dass ein Suchtreffer in dem Dokument zwar gefunden, aber beim Aufruf des Treffers aus der Suche dann nicht gleich gesehen wird, weil der Treffen in einem geschlossenen Accordion hängt.

Verschobener Issue aus https://github.com/RRZE-Webteam/FAU-Einrichtungen/issues/344

**Comment by cassandre** [comment]
Der Schalter ist schon eingebaut: expand-all-link="true".
Sprungmarke geht auch name="rwfak" und dann www.meine-url.de/meine-seite/#rwfak.
Funktioniert leider noch nicht innerhalb der Seite, also wenn der Link auf der selben Seite steht. Daher lasse ich den Issue mal offen.

**Comment by cassandre** [comment]
Funktioniert mittlerweile.
