### ISSUE TITLE
Auswahlmodi für [columns] (Verbesserungsvorschlag)

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/rrze-elements#103]
Der Shortcode [columns] ist bereits wirklich super, jedoch wäre es ideal, wenn man noch mehr Auswahlmöglichkeiten erhält, wie die Spalten auf mobilen Geräten dargestellt werden, damit man zu enge Textblöcke verhindern kann.

Der Wunsch wäre also quasi, dass man für tablet und handy noch einstellen kann, ob zweispaltig oder einspaltig oder gemischt ausgegeben werden soll. Bei drei Spalten kann das zwar zu etwas mehr weißem Raum führen aber die Textbreite kann ideal eingestellt werden. Ideal fände ich es, wenn zwischen 45 - 75 Zeichen pro Textblock vorhanden sind. Aber das ist natürlich nur Wunschdenken. Ist wie gesagt nur ein Wunsch/Vorschlag für die Zukunft
![columns](https://user-images.githubusercontent.com/58593037/98346651-92407800-2016-11eb-8991-2f94fce1f040.png)

**Verwendeter Code im Beispiel:**
[columns]
[column]
Block 1>
[/column]
[column]
Block 1
[/column]
[column]
Block 3
[/column]
[/columns]

**Comment by cassandre** [comment]
Die Umbrüche passieren automatisch. Im Moment ist die Mindestbreite für die Columns mit 160px angegeben. Ich könnte es auf 180px oder 200px erhöhen (200px wären im FAU-Theme ca. 45 Zeichen). 200px wäre schöner, 180px hätte den Vorteil, dass auch im FAU-Theme mit eingeschalteter Sidebar oder Seitennavi wenigstens drei Spalten nebeneinander passen.

Was ich nicht machen würde, wären Blöcke, die nur einen Teil der Bildschirmbreite einnehmen.

**Comment by lukasniebler** [comment]
Die Frage ist ja, wie lange es noch dauert, bis das FAU Theme überarbeitet wird zwecks full-width. Anschließend wären ja auch drei Spalten mit 200 px machbar. Ansonsten könnte man es ja Übergangsweise erst mal bei 180 px belassen. Dreispaltig ist natürlich schon super, weil dann das Bild mit der Breite 1 und der Text daneben mit Breite 2 festgelegt werden kann. Ansonsten wäre das wieder problematisch für die Leute, die schon Ihren Inhalt dreispaltig konzipiert hatten wo anschließend das eine Element in eine extra Zeile rutscht..
