### ISSUE TITLE
Accordion - Festgelegte Sprache im Inhaltsbereich berücksichtigen für den "Alle öffnen" Button

### ISSUE THREAD

**Issue by ghost** [RRZE-Webteam/rrze-elements#104]
Liebes RRZE Team,

ich habe die Sprache im Inhaltsbereich auf Englisch gestellt:

![image](https://user-images.githubusercontent.com/44059562/98545103-40f1ec00-2295-11eb-9de6-f32aae480c6f.png)

Es wäre schön, wenn der Text "Alle öffnen" durch den Schalter expand-all-link=“true“ auch der Sprache im Inhaltsbereich entsprechen würde:

![image](https://user-images.githubusercontent.com/44059562/98545050-29b2fe80-2295-11eb-9296-470f77e64a99.png)

Liebe Grüße
Andy

**Comment by cassandre** [comment]
Ist im nächsten Update drin, wird allerdings nur für deutsch und englisch funktionieren, da die Übersetzung in dem Fall manuell eingepflegt werden muss.
