### ISSUE TITLE
pull-left quote im Event-Theme mit Text alignen

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/rrze-elements#105]
Im Event-Theme wird der Einschub außerhalb des Textfensters dargestellt. Kundenwunsch wäre, dass es sich im Event-Theme mit dem linken Text-Rand alignen lässt.
![grafik](https://user-images.githubusercontent.com/58593037/99499117-af5f3a00-2978-11eb-82a6-32c4641dc234.png)

aus Helpdesk ( http://go.fau.de/9psls )

**Comment by cassandre** [comment]
Das ist genau der Sinn des Einschubs, dass er herausragt und dadurch ins Auge fällt. Ist keine Erfindung von mir, gibt es auch in anderen Web-Themes (z.B. auf zeit.de).
Nur im FAU-Theme hatte ich ihn bündig gemacht, weil dort kein Platz ist.
