### ISSUE TITLE
Alert - Textfarbe ändert sich auf Standardwert nach dem ersten Absatz.

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/rrze-elements#106]
Wenn ein Alert angelegt wird, ändert sich die Schriftfarbe nach dem ersten Absatz auf den Standardwert des Themes zurück.
Bei [alert style="danger"]...[/alert] sieht das ganze dann so aus:
![grafik](https://user-images.githubusercontent.com/58593037/100112851-02048e80-2e70-11eb-86ab-e8589da70033.png)

Übernommen aus Helpdesk: http://go.fau.de/9p15g Weitere Informationen im Ticket.

**Comment by cassandre** [comment]
Mittlerweile gefixt.
