### ISSUE TITLE
Subpages-Accordion  - Alter "Assistant"-Shortcode  

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-elements#107]
"Aus alten Zeiten" haben wir im Theme noch ein [assistant]-Shortcode.

Dieses übernimmt als Wert id=""  die Id eines Page.

Bei einer Ausführung von [assistant id=""] wird an der Stelle ein Accordion mit Tabs erstellt.
Die jeweiligen Tabs enthalten dann den Inhalt aller Pages, die der Page mit der Eingangsid hierarchisch untergeordnet sind.

Siehe hierzu auch im Theme: includes/shortcodes.php,   function fau_assistant().

Es wäre schön, wenn diese Funktion auch in Elements eingehen könnte.

Hierbei wäre es aber notwendig, dass die Accordions im Elements auch Tabs unterstützen.

**Comment by cassandre** [comment]
In 3a3d0913f8d19ba611f4b6983551c1ff005a4aaf integriert und erweitert:
* Accordion-Farbe
* Expand-All-Link
* Ausschluss Selbstreferenz (verursacht sonst Timeout)

Kann aus FAU-Einrichtungen entfernt werden.
