### ISSUE TITLE
Columns-Shortcode funktioniert nicht mehr

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/rrze-elements#111]
Seit Freitag Abend scheint die Columns-Funktion nicht mehr korrekt zu funktionieren.
Spezifischer Kundenfall im Helpdesk:

http://go.fau.de/9qfbm

Shortcode scheint korrekt angelegt zu sein.

**Comment by cassandre** [comment]
Korrigiert in bb8896fff1b95320b768995b2c7b586b68ae5993
