### ISSUE TITLE
Custom News und div class=example

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/rrze-elements#113]
Durch Zufall drüber gestolpert:

Das Div für die Anleitungsseiten mit class="example" wird wohl durch die Custom news vorzeitig geschlossen.

(Ich entferne das div-Element vorerst einfach mal von der Anleitungsseite)

![grafik](https://user-images.githubusercontent.com/58593037/108178752-17065c00-7105-11eb-889c-dfc955cb3334.png)

![grafik](https://user-images.githubusercontent.com/58593037/108178790-22598780-7105-11eb-92a4-a86ada2c65d0.png)

**Comment by lukasniebler** [comment]
Ahh wahrscheinlich geht das jetzt einfach über das Attribut divclass="", oder? - Gerade erst gesehen

**Comment by cassandre** [comment]
Nee, war schon ein Fehler im Code (bzw. Zusammenspiel zwischen unglücklicher CSS-Definition im FAU-Theme und einem überzähligen column-Shortcode im Code). Korrigiert in 37e8374b69f8cb041eed40a51a8428e942d85529.
