### ISSUE TITLE
Column span funktioniert nicht im FAU Events-Theme

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/rrze-elements#115]
(Zu: http://go.fau.de/9qfbm )
![grafik](https://user-images.githubusercontent.com/58593037/108207380-f69bc900-7127-11eb-986f-12f10e12c973.png)

Spaltenelemente können mit [column span="3"] bzw. span="1" nicht eingestellt werden.
Die Ausgabe erfolgt trotzdem als 50:50

Konkretes Fallbeispiel mit Seitenlink im Helpdesk-Fall.

**Comment by cassandre** [comment]
[column span="x"] funktioniert nur, wenn bei [columns] die Anzahl der Spalten angegeben wurde.
In diesem Fall also
````` 
[columns number="4"]
[column span="1"] … [/column]
[column span="3"] … [/column]
[/columns] 
`````
