### ISSUE TITLE
font-size/line-heights korrigieren

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-elements#124]
Bitte die font-size & line-height nur noch in "**rem**" angeben und dabei **line-height = font-size * 1.5.**

![grafik](https://user-images.githubusercontent.com/1070669/116706990-ba090b00-a9bd-11eb-8321-ab6239ec917d.png)

Wenn der Wert auf "rem" angegeben ist, ist der Schriftfont stets nur noch von der Angabe html-Tag abhängig und kann darüber später viel einfacher global gesteuert werden).

Ggf. nutze das mixin, welches ich in FAU -Einrichtungen hab:

```

@function px2rem($font-size, $base-font-size: $font-size-gridbase) {
	@return $font-size / $base-font-size + rem;
}

@mixin px2rem($font-size, $base-font-size: $font-size-gridbase, $line: $font-size * 1.5) {
  font-size: px2rem($font-size, $base-font-size);
  line-height: ($line / $base-font-size) + rem;
}
```

**Comment by cassandre** [comment]
Erledigt in f2e3240.
