### ISSUE TITLE
Blogroll-Darstellung erweitern

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/rrze-elements#125]
Wir möchten gerne einen Newsticker einrichten, der Blogbeiträge einer bestimmten Kategorie nur mit verlinkter Überschrift und ohne Bild und Teaser als Liste anzeigt.
Wir bräuchten etwas wie hide="image, teaser" show="list"

**Comment by cassandre** [comment]
Reicht die Darstellung dislay="list"  nicht aus?
Siehe https://www.wordpress.rrze.fau.de/plugins/fau-und-rrze-plugins/elements/news/ ganz unten.

**Comment by wrcg** [comment]
ja, so soll es aussehen, aber es werden hier die echten Links zu den Beiträgen gesetzt. Wir wollen aber die externen Links, die wir in den Beiträgen angeben, an dieser Stelle haben.

**Comment by cassandre** [comment]
D.h. der Blogbeitrags-Titel soll mit einer (beliebigen) URL aus dem Content-Bereich verlinkt werden? Das ist leider nicht möglich.

**Comment by wrcg** [comment]
oh, da hab ich mich wohl falsch ausgedrückt. 
Es soll der Link verwendet werden, der im Feld "Externer Link" angegeben wird. Dieser wird bereits bei der Blogroll korrekt verwendet und auch beim Shortcode content-slider. 
Vielleicht doch nur ein Bug, dass es bei custom-news nicht klappt?
<img width="514" alt="2021-05-04 11_42_36-Beitrag bearbeiten ‹ Friedrich-Alexander-Universität Erlangen-Nürnberg — WordPre" src="https://user-images.githubusercontent.com/9526974/116986318-ebd7e580-accd-11eb-9fca-5f00fd7a957f.png">

**Comment by cassandre** [comment]
Ah, OK, das ist FAU-Theme-spezifisch, die Funktion war mir nicht so präsent.
Wäre in dem Fall natürlich sinnvoll, das so umzusetzen. Ich denke, es wird mittelfristig ein Update geben, wo ich das mit rein nehme. Ich kann allerdings noch nicht versprechen, wie bald das geschehen wird.
