### ISSUE TITLE
Responsivität bei Custom News mit Column

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-elements#126]
Die Seite ist in den Custom News/Columns nicht responsible, bzw. bricht nicht entsprechend mit einem Flex Grid Ansatz um;
Beispiel: intern-fau-de/blog

![grafik](https://user-images.githubusercontent.com/1070669/117967507-a726fc80-b314-11eb-9671-60296ac621d6.png)

**Comment by cassandre** [comment]
Kann ich nicht reproduzieren (Firefox Dev, Chrome, Safari). Mit welchem Browser und Betriebssystem tritt das auf?
