### ISSUE TITLE
Absatzklassen / Alerts mit Hintergrund

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-elements#13]
vgl:
https://www.beta.wordpress.rrze.fau.de/texte/absatzklassen/
https://getbootstrap.com/docs/3.3/components/#alerts

Bitte baue noch eine Kombination der Absatzklassen mit den Alerts von Bootstrap, wobei auch die Hintergrundfarbe beeinflusst werden sollte. Zusätzlich zu den 4 von Bootstrap brauchen wir auch eine Absatzklassen mit der Hintergrundfarbe vom hellen grau ($colorStandardHellgrau:	    #e9edf2; )
vgl. https://github.com/RRZE-Webteam/FAU-Einrichtungen/issues/488

**Comment by cassandre** [comment]
Man kann problemlos eine Absatzklasse in einen Alert packen:
`[alert style="danger"][notice-attention]Hier der Text[/notice-attention][/alert]`
