### ISSUE TITLE
alt-Text für Button-Links anpassen

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/rrze-elements#132]
Wenn ich auf einer Seite mehrere Buttons verwende, die auf unterschiedliche Seiten gehen, aber den gleichen Text haben (z.B. Weitere Infos), dann zeigt mit Siteimprove einen Fehler an. Deswegen wäre es praktisch, wenn ich für Buttons eigene alt-Texte vergeben kann, damit solche Seiten barriereärmer werden.

**Comment by xwolfde** [comment]
@cassandre  wenn es ein Text ist, dann title-Attribut verwenden
