### ISSUE TITLE
Accessibility-Problem bei einigen Bildunterschriften

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/rrze-elements#139]
Siteimprove zeigt bei einigen (nicht allen) Bildunterschriften einen Accessibility-Fehler an: "Die Zeilenhöhe liegt unter dem Mindestwert".
Zum Beispiel auf dieser Seite: https://www.fau.de/outreach/wissenschaft-fuer-buergerinnen-und-buerger/

Siteimprove sagt: "Die line-height (Zeilenhöhe) für Absätze sollte mindestens das 1,5-Fache der Schriftgröße betragen."

**Comment by xwolfde** [comment]
Halt, nein.

Das Problem liegt an rrze-elements:
Es überschreibt die font-size des Textes und macht somit die line-height falsch.
![grafik](https://user-images.githubusercontent.com/1070669/142014132-0db50e9f-ad31-4516-9c6a-db350f401639.png)

**Comment by cassandre** [comment]
in f2e324029a92d67966db7bcee75d3f4a6638761f erledigt.
