### ISSUE TITLE
Fehler der Akkordion-Darstellung (aus Helpdesk)

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/rrze-elements#143]
s. http://go.fau.de/9r0fp

Abstand der einzelnen Fächer zueinander ist seit dem letzten update ungewöhnlich groß.

<img width="1474" alt="Bildschirmfoto 2021-11-24 um 09 53 05" src="https://user-images.githubusercontent.com/58593037/143205673-22693f46-8e01-4eaa-b892-f6e5677dc146.png">

(Ist ~~es~~ ein Bug ~~oder zwecks Barrierefreiheit ein Feature?~~)

**Comment by lukasniebler** [comment]
s. http://go.fau.de/9r0fg

**Comment by cassandre** [comment]
in #144 erledigt.
