### ISSUE TITLE
Columns-Grid bei kleinen Auflösungen

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-elements#146]
Bei kleinen Auflösungen (<768px) scheint es bei dem zweispaltigen Columnsgrid kein warp zu geben, bzw. keine min-width pro Spalte.
Hier ggf mit flex grid ein min-width vorgeben pro Inhaltsbereich und den wrap erlauben.

Siehe: https://github.com/RRZE-Webteam/FAU-Einrichtungen/issues/851

**Comment by cassandre** [comment]
Es gibt schon ein Wrap ("Warp" kann Elements allerdings in der Tat noch nicht ;-) ): Min-width ist angegeben, liegt bei 180px und funktioniert auch. War bewusst so gewählt hat, und bislang war es auch für alle OK.

**Comment by xwolfde** [comment]
Hm. Bei der Blogroll hab ich mit dem Symbolbildern der Artikel auch bei der 480Pixel Darstellung einen Umbruch gebaut, dass diese dann schon wrappen. Ich glaub es wäre gut, wenn es hier auch so wäre.

Nutzt du da eine flex grid?

**Comment by cassandre** [comment]
Ja, das ist Flex mit min-width=180. D.h. solange eine Spalte kleiner als 180px ist, wird umgebrochen.
Standard ist eigentlich min-width=200px, nur bei FAU-Themes ist es 180px. Ich muss noch mal schauen, wieso ich da extra was für die FAU-Themes eingebaut habe – muss ja einen Grund dafür gegeben haben.
