### ISSUE TITLE
Feature Request für Zeitleiste

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-elements#147]
Aus Anfrage von KA:

_Dazu hätte ich noch eine Bitte: Könntet ihr bitte doch noch zwei Buttons einrichten, um direkt zum Ende (bzw. direkt wieder zum Anfang) zu springen. Momentan muss man noch jedes einzelne Jahr durchklicken._

**Comment by cassandre** [comment]
Duplikat von #135.
