### ISSUE TITLE
Sliderpfeile undeutlich

### ISSUE THREAD

**Issue by cassandre** [RRZE-Webteam/rrze-elements#15]
Die Pfeile nach links und rechts im Slider erscheinen erst wenn man mit der Maus über den Bereich hovered.
Dann aber sind sie auch noch sehr unscheinbar und bei einem dunklen Hintergrund gar nicht leicht erkennbar.

**Comment by xwolfde** [comment]
Bei der FAU hab ich mich ab der neuen Version mit einem text-shadow beholfen.

**Comment by cassandre** [comment]
In https://github.com/RRZE-Webteam/rrze-elements/commit/66be9602f5bbb154624a116f9c15b532ff8fc3ec gefixt.
