### ISSUE TITLE
Farbe von Links in Alertbox

### ISSUE THREAD

**Issue by MaStFAU** [RRZE-Webteam/rrze-elements#151]
Bei Alertboxen mit dunkler Hintergrundfarbe hilft die Option` font="light"`. Die Schriftfarbe wird dadurch in der Regel auf weiß gesetzt. Bei Links ist die Schriftfarbe dann allerdings grau und rot unterstrichen. Die Lesbarkeit ist nur bedingt gegeben.
Lassen sich diese Farben manuell ändern für die Alertbox Inhalte?

```
[alert color="#002F6C" font="light" ]
<h2>Minimalbeispiel</h2>
<a href="http://www.fau.de">Link zur FAU Website</a>
[/alert]
```

**Comment by xwolfde** [comment]
Ggf. wäre es sinnvoll "einfach" ausgehend von der gesetzten hex-color in color="" den richtigen Kontrast-Hintergrund mit einem Konstrastabstand >=7 berechnen zu lassen @cassandre 

Dazu gibt es in SASS schon Libraries. Müsste aber auch via PHP machbar sein, wenn man inline-style für die background setzen will.

**Comment by cassandre** [comment]
@xwolfde Da hat einfach nur das text-decoration-color aus den Fakultätsfarben zwischengefunkt. 

Die helle Linkfarbe ist jetzt fast weiß. Mehr Kontrast geht nicht. Eine extra Bibliothek dafür wäre absoluter Overkill.
