### ISSUE TITLE
Font-Awesome 3 mal geladen...

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-elements#153]
Können wir hier etwas optimieren?
(Font Awesome icons werden 3 mal geladen)
![grafik](https://user-images.githubusercontent.com/1070669/145428013-0f616639-dd5a-4449-9315-e60fb95129de.png)

**Comment by cassandre** [comment]
Ist in der letzten Version komplett aus Elements rausgeflogen.
