### ISSUE TITLE
Spalten-Columns bitte auf flex grid umstellen

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-elements#155]
Bei den 
.four-columns-one, .four-columns-three, .four-columns-two, .three-columns-one, .three-columns-two, .two-columns-one Classes wird noch float als Methode verwendet.

Bitte auch hier auf flex grid umstellen.

**Comment by cassandre** [comment]
Der Shortcode ist veraltet und ist nur noch der Abwärtskompatibilität halber enthalten. Der neue Shortcode ist wesentlich einfacher und basiert bereits auf flex: https://www.wordpress.rrze.fau.de/plugins/fau-und-rrze-plugins/elements/mehrspaltiger-inhalt/

Den alten Shortcode anzupassen, wäre aufwändig, da kein umgebendes div vorgesehen ist, dem man die flex-Eigenschaft geben könnte. Der Aufwand lohnt sich für das veraltete Element nicht.
