### ISSUE TITLE
Probleme mit der Accordeon-Darstellung auf der RRZE-Seite

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/rrze-elements#158]
🎫 Verknüpfter Helpdesk-Fall: http://go.fau.de/9r66a
Auf der Formular-Seite sieht man das Problem recht gut:

https://www.rrze.fau.de/infocenter/kontakt-hilfe/formulare/#idmkennung

Die Sidebar sorgt dafür, dass Akkordeonfächer erst nach der Sidebar anfangen.
Zudem glaube ich, dass auf der RRZE-Seite die Darstellung nicht geplant ist. (Dachte erst es wär ein Feature)
<img width="1153" alt="Bildschirmfoto 2022-01-13 um 14 13 54" src="https://user-images.githubusercontent.com/58593037/149336692-dc964057-d41c-49f5-9723-251caab72719.png">
(Getestet in Safari)

**Comment by lukasniebler** [comment]
🎫 http://go.fau.de/9r7c7 - Verknüpfter Fall aus Helpdesk
( 🐌 Eilt nicht ). Melder sind informiert, dass das Problem erst im Verlauf der nächsten Woche behoben wird.
Schönes Wochenende. Betrifft nur RRZE-Seite.

**Comment by cassandre** [comment]
Erledigt in 9b68f6da25e5ac62ba5b00b0cb773220af6154b3 
und [https://gitlab.rrze.fau.de/rrze-webteam/rrze-2019/-/merge_requests/42](https://gitlab.rrze.fau.de/rrze-webteam/rrze-2019/-/commit/a5f1cd37a5fdbb5457925078e669d58f32d5db2f)
