### ISSUE TITLE
Klasse example

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/rrze-elements#163]
div class="example"

- [x] Der Farbton der gestrichelten Umrandung dürfte ruhig kräftiger sein, im Zentral-Theme ist der Farbton sonst identisch mit Alerts
- [x] Vielleicht kann man die Klasse example doch klickbar machen? Es gibt immer mal wieder Beispiele (Akkordeonfächer), (Buttons) wo man sonst in der Anleitung die Hover/Klick Effekte nicht ausprobieren kann.
- [x] Ich nutz die Klasse auch gerne für die Screenshots. Allerdings kann man dann die Bilder natürlich nicht mehr vergrößern, da die Klasse example das klicken ja verhindert im div.

// Alternativ wäre auch eine gesonderte Klasse für Anleitung-Screenshots mit einem ähnlichen gestrichelten Rahmen cool, wo dann das klicken / vergrößern möglich ist.

Beispiel:
https://www.urlaubaufsagrotan.test.rrze.fau.de/anleitungen/schnellstart-fau-einrichtungen/portale-menuefuehrung-und-socialmedia/

<img width="1941" alt="Bildschirmfoto 2022-01-21 um 14 35 20" src="https://user-images.githubusercontent.com/58593037/150536189-d0243228-14d9-4798-963f-85cb191d7ad8.png">

**Comment by cassandre** [comment]
Wird als Sonderform des Alert umgesetzt.
- neues Attribut: `title="Example"`
- Default-Style (-> wenn title gesetzt) wie im Example-div
- Hintergrund- und Border-Farbe kann man bereits setzen
- ggf. noch `border-style` (-> dashed, dotted...) ergänzen

**Comment by xwolfde** [comment]
Frage wg. Abwärtscompatibilität:
Wenn ich aus dem Theme die CSS Klasse example rausnehme, wird sie durch das Elements Plugin noch geliefert?
Andernfalls müsste ich überall dort, wo ich bislang ein `<div class="example">...</div>` setzte, das Shortcode von Hand ändern.

Wäre statt `[alert]` in diesem Fall nicht auch` [code] `sinnvoll?

**Comment by cassandre** [comment]
Ist jetzt abwärtskompatibel eingebaut, die Styles können aus dem FAU-Theme entfernt werden. Funktioniert sowohl mit `<div class="example">...</div>` als auch mit `[alert style="example"]...[/alert]`.
Nur den Rahmen habe ich etwas dunkler gemacht, als im Original: `--color-TextLight`.

**Comment by xwolfde** [comment]
Aktuell muss das CSS im Themes bleiben, da er sonst nicht verfügbar ist, wenn man die Class direkt via HTML-Aufruf einbindet.
Aus Elements wird die Class nur dann bereitgestellt, wenn zuvor ein RRZE Elements Shortcode verwendet wurde: Denn erst danach wird das CSS von Elements geladen.
