### ISSUE TITLE
Buttons - Ghostbuttons

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/rrze-elements#164]
Als neues Feature - Ghostbuttons wie im FAU Theme

**Comment by cassandre** [comment]
Was mir grad einfällt: Kann man das nicht über `color`, `font` und `border-color` lösen?
-> https://www.wordpress.rrze.fau.de/plugins/fau-und-rrze-plugins/elements/buttons/#collapse_2

Oder soll ich ein `style="ghost"` ergänzen, weil einfacher?

**Comment by lukasniebler** [comment]
Also eigentlich reicht color, Font & border-color. 

(Einen Darkmode haben wir ja erstmal eh nicht) /

**Comment by xwolfde** [comment]
style="ghost" wäre aber eine schöne vereinfachung. Bei color="" kann man sicher viel falsch machen...

**Comment by cassandre** [comment]
Na gut, es gibt ab dem nächsten Update (1.22.4) auch `style="ghost"` (e3c1715fd0909ef2a1792e6b2049c536d9328bee).

`color=""` wird es trotzdem weiterhin geben – bislang gehen die Leute da ganz vernünftig mit um.
