### ISSUE TITLE
Akkordeons: Keine Sprungmarken (mehr?)

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/rrze-elements#169]
Die Sprungmarken, mit denen man direkt auf Akkordeons verlinken konnte, funktionieren nicht mehr. Auch dann nicht, wenn eine name vergeben wurde. 
Beispielseite: https://www.fau.de/corona/3g-regel/

**Comment by cassandre** [comment]
Was genau funktioniert nicht? https://www.fau.de/corona/3g-regel/#nachweis-der-genesung wird bei mir korrekt angesprungen.

**Comment by AndiWebred** [comment]
wenn ich auf die seite gehe und ein akkordeon anklicke bekomme ich keine sprungmarke angezeigt. wenn ich deinem link folge, geht das akkordeon auf, der link bleibt aber gleich, auch wenn ich andere akkordeons öffne.

**Comment by cassandre** [comment]
OK, dann weiß ich Bescheid.
Dann kann ich endlich die Sprungmarken auf ID umstellen (#131) – das hat im alten FAU-Theme wegen eigener JS-Skripten nicht funktioniert.

**Comment by xwolfde** [comment]
Bitte dran denken, dass die Id tatsächlich auch unique sein muss, selbst wenn dasselbe Accordion mehrfach in der Seite auftaucht. Die Gefahr ist bei dem Setzen von named-Anchors gegeben, wenn der Autor den Teil copy&pastet...
