### ISSUE TITLE
PHP Notices

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-elements#17]
Ich bekomme unangenehme Meldungen mit der aktuellen Version:

"Notice: Trying to get property of non-object in /var/www/vhosts/wordpress/websource/wp-content/plugins/rrze-elements/includes/main.php on line 72

Notice: Trying to get property of non-object in /var/www/vhosts/wordpress/websource/wp-content/plugins/rrze-elements/includes/main.php on line 73

Notice: Trying to get property of non-object in /var/www/vhosts/wordpress/websource/wp-content/plugins/rrze-elements/includes/main.php on line 74

Notice: Trying to get property of non-object in /var/www/vhosts/wordpress/websource/wp-content/plugins/rrze-elements/includes/main.php on line 75

Notice: Trying to get property of non-object in /var/www/vhosts/wordpress/websource/wp-content/plugins/rrze-elements/includes/main.php on line 76

Notice: Trying to get property of non-object in /var/www/vhosts/wordpress/websource/wp-content/plugins/rrze-elements/includes/main.php on line 77

Notice: Trying to get property of non-object in /var/www/vhosts/wordpress/websource/wp-content/plugins/rrze-elements/includes/main.php on line 78

Notice: Trying to get property of non-object in /var/www/vhosts/wordpress/websource/wp-content/plugins/rrze-elements/includes/main.php on line 79

Notice: Trying to get property of non-object in /var/www/vhosts/wordpress/websource/wp-content/plugins/rrze-elements/includes/main.php on line 80

Notice: Trying to get property of non-object in /var/www/vhosts/wordpress/websource/wp-content/plugins/rrze-elements/includes/main.php on line 81

Notice: Trying to get property of non-object in /var/www/vhosts/wordpress/websource/wp-content/plugins/rrze-elements/includes/main.php on line 82

Notice: Trying to get property of non-object in /var/www/vhosts/wordpress/websource/wp-content/plugins/rrze-elements/includes/main.php on line 83

Notice: Trying to get property of non-object in /var/www/vhosts/wordpress/websource/wp-content/plugins/rrze-elements/includes/main.php on line 84

Notice: Trying to get property of non-object in /var/www/vhosts/wordpress/websource/wp-content/plugins/rrze-elements/includes/main.php on line 85

Notice: Trying to get property of non-object in /var/www/vhosts/wordpress/websource/wp-content/plugins/rrze-elements/includes/main.php on line 86

Notice: Trying to get property of non-object in /var/www/vhosts/wordpress/websource/wp-content/plugins/rrze-elements/includes/main.php on line 87"

**Comment by xwolfde** [comment]
(Bei Ausführen der Suche)

**Comment by cassandre** [comment]
Sollte sich mittlerweile erledigt haben.
