### ISSUE TITLE
Links auf Accordion

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/rrze-elements#171]
seit der Umstellung (?) werden in der URL die Anker/Namen der Accordionbalken nicht mehr angezeigt. Das führt dazu, dass man bei Erklärungen in Mails nicht direkt auf den entsprechenden Accordionbereich verlinken kann, da man den entsprechenden Link im Browser nicht kopieren kann. Kann das wieder aktiviert werden?

**Comment by lukasniebler** [comment]
🎫 http://go.fau.de/9se3t
