### ISSUE TITLE
Social-Media-Icons

### ISSUE THREAD

**Issue by cassandre** [RRZE-Webteam/rrze-elements#175]
für Social-Media-Links, die im Fließtext eingebettet werden sollen.

**Comment by xwolfde** [comment]
Also so etwas wie: 

```
&[href*="twitter.com"]:focus:before,
	&[href*="twitter.com"]:hover:before {
	    background-image: svg-twitter($socialmedia_icon_color_hover);
	}

```

**Comment by cassandre** [comment]
Ja genau. Im FAU-Theme sind die SVGs ja vielleich eh schon im Footer vorhanden? 
Umsetzen würde ich das dann in etwa so: `[twitter account="accountname"]` bzw. `[linkedin url="https://www.linkedin.com/company/invrtual"]`.

(Hatte eigentlich schon mal überlegt, auf diese Weise alle Fontawesome-Icons per Shortcode mit optionalem Link zur Verfügung zu stellen... `[fa icon="..." url="..."]`)

**Comment by xwolfde** [comment]
> Im FAU-Theme sind die SVGs ja vielleich eh schon im Footer vorhanden?

In diesen Fall nicht:
Bei den SVGs in CSS handelt es sich um Background-SVGs. Die sind nicht im HTML, also im Footer.
Im Footer sind nur die SVGs, die inhaltstragender Teil des Contents sind.

**Comment by xwolfde** [comment]
Wenn es darum geht, Links zu Ressourcen mit Icons zu versehen, sollten wir uns ggf. auch andere Medien anschauen. Wir haben leider auch noch das (ärgerliche) MIme Type Links Plugin.
Ggf. macht es SInn, das zusammen zu fassen.

**Comment by cassandre** [comment]
Kann man seit https://github.com/RRZE-Webteam/rrze-elements/commit/3ff222c38023d3f459f0dcf2319105ac2d419012 auch gut von Hand erledigen:
`<a href="https://twitter.com/accountname">[icon icon="twitter"] Mein Twitteraccount</a>`
Reicht das?

**Comment by stolpervogel** [comment]
Hallo Frau Bothe,

Sie müssen mich hier glaub ich nochmal abholen. Funktioniert dieses Feature jetzt schon unter „RRZE-Elements einfügen“ oder kommt das mit dem nächsten Update?
Entschuldigen Sie die Frage, ich bin mit der Vorgehensweise „github zu Umsetzung in Wordpress“ nicht vertraut.

Beste Grüße
Kerstin Reuß

Von: Barbara Bothe ***@***.***>
Gesendet: Mittwoch, 27. Juli 2022 14:51
An: RRZE-Webteam/rrze-elements ***@***.***>
Cc: Reuß, Kerstin ***@***.***>; Manual ***@***.***>
Betreff: Re: [RRZE-Webteam/rrze-elements] Social-Media-Icons (Issue #175)


Closed #175<https://github.com/RRZE-Webteam/rrze-elements/issues/175> as completed.
