### ISSUE TITLE
Accessibility-Problem mit mehreren Custom-News

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/rrze-elements#176]
Auf Seiten mit mehreren Custom-News-Blöcken (also vor allem hier: https://www.fau.de/newsportal/) wird uns ein Accessibility-Problem angezeigt, weil die Buttons "Weitere Artikel" zu unterschiedlichen Zielen führen.

Wäre es eine Möglichkeit, die Buttons mit einem aria-label zu ergänzen? 
aria-label="Weitere Artikel: Kategoriename/Schlagwortname"

**Comment by cassandre** [comment]
Done.
