### ISSUE TITLE
Vorschlag: Collapsibles hstart="3" als Standard

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/rrze-elements#178]
Momentan sind die Collapsibles h2-Überschriften, wenn nichts anderes angegeben. Macht es aber nicht mehr Sinn, den Standard als h3 anzugeben? Meist ist ja die h2 die Subhead. Von der Logik kämen dann die Collapsibles darunter also als h3.

**Comment by xwolfde** [comment]
Hatten wir vorher schon... Wir haben es auf h2 geändert, weil die Mehrheit der Webmaster bei den Webauftritten keine h2 vor dem Accordion nutzte. Dadurch kam es zu vielen Fehlern, weil die h2 fehlte.

**Comment by AndiWebred** [comment]
Hehe, alles klar. Dann lassen wir es wegen mir so, wie es ist.
