### ISSUE TITLE
Collapsibles: expand-all und hstart funktionieren nicht zusammen

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/rrze-elements#179]
Die Kombination [collapsibles expand-all-link="true" hstart="4"] funktioniert nicht. Der expand-all-button blockiert das hstart-Attribut, sodass die Überschriften des Akkordeons als h2 ausgegeben werden.

Beispiel: https://www.fau.de/corona/hygiene/

**Comment by cassandre** [comment]
Kann ich nicht nachvollziehen. Überall, wo hstart=4 angegeben ist, wird auf der genannten Beispielseite die Überschrift entsprechend ausgegeben. Beim letzten Accordion ("Regelungen zu spezifischen Themen") ist kein hstart angegeben, daher wird hier standardmäßig h2 gesetzt.
