### ISSUE TITLE
Custom News | Darstellung auf engerem Raum

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/rrze-elements#183]
Die Darstellung mit einer Spalte könnte auf Inhaltsseite mit Navi links beim Anleser noch bisschen breiteren Text darstellen. (Auf dem Standardtemplate sieht es perfekt aus).

https://www.wordpress.rrze.fau.de/plugins/inhaltsseiten-mit-funktionen-erweitern/elements/news/custom-news-beispielumsetzung/

<img width="1446" alt="Bildschirmfoto 2022-04-08 um 14 13 50" src="https://user-images.githubusercontent.com/58593037/162433455-ff3506f6-f068-4433-afde-46272d5c75e1.png">

**Comment by cassandre** [comment]
Das lässt sich mit z.B. `type="cols_2-1"` auf das jeweilige Layout anpassen. Standard ist `cols_3-1`.
