### ISSUE TITLE
Switch für Dokumentationen und Co. 🐛

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/rrze-elements#185]
Wie findet Ihr die Idee, für die Dokumentation und Co. sowas wie Hier zu benutzen:
<img width="1013" alt="Bildschirmfoto 2022-04-12 um 09 40 36" src="https://user-images.githubusercontent.com/58593037/162907221-d18d1236-2cb2-4be7-b391-7f443bf83f63.png">

https://wiki.selfhtml.org/wiki/HTML/Tutorials/Listen/Beschreibungslisten

Da könnte man dann zwischen Shortcode / Code und Vorschau hin und herrwechseln als Nutzer.
In der WordPress-Dokumentation hatte ich sowas auch mal in schöner gesehen. (Hab die URL aber nicht mehr gefunden in den letzten Wochen).

Nur eine Idee für die Zukunft.

**Comment by cassandre** [comment]
Die Clips von Codepen machen das ziemlich genial, z.B. hier:
https://css-tricks.com/cut-corners-using-css-mask-and-clip-path-properties/#aa-circular-cut-out

Da kann man jeweils HTML/CSS/JS ein- und ausschalten. Also nicht nur Tabs wechseln, sondern auch beides zweispaltig nebeneinander anschauen. Aber Tabs in einem ersten Schritt wären sicher schon mal klasse, und viel übersichtlicher!

**Comment by lukasniebler** [comment]
Ja das klingt super. Das würde so manche Anleitungsseite schon viel übersichtlicher machen. 🦑

**Comment by cassandre** [comment]
Lesezeichen: https://inclusive-components.design/tabbed-interfaces/
