### ISSUE TITLE
Akkordeons werden in der Leseansicht nicht angezeigt und vorgelesen

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/rrze-elements#187]
Wir haben folgende Rückmeldung per Mail bekommen:

"Mir ist aufgefallen, dass auf der Affiliationsseite das Akkordeon bei der Leseansicht nicht angezeigt wird. Man sieht das Akkordeon nur, wenn es vorher aufgeklappt wurde. Außerdem ist mir aufgefallen, dass beim Vorlesen des Akkordeons die Überschriften fehlen."

Die Kollegin arbeitet auf dieser Seite: https://www.fau.de/research/service-fuer-forschende/publizieren-und-open-access/tipps-zur-korrekten-affiliation/
Aber vermutlich gilt das für alle Akkordeons.

**Comment by cassandre** [comment]
Das Problem ist, dass die Browser selbst – und jeder Browser unterschiedlich – entscheiden, welche Teile der Seite sie im Lesemodus anzeigen, und welche nicht. Das kann man auch nicht entwicklerseitig beeinflussen. 
Ein div mit zu wenig Inhalt wird weggelassen. Buttons grundsätzlich auch. Daher habe ich die Accordion-Titel (das sind wegen der Barrierefreiheit Buttons) jetzt extra für den Lesemodus in ein sonst unsichtbares span gedoppelt. Für die Inhalte der Accordionfächer müssen wir auf die Browser hoffen.
Ist im nächsten Update drin.
