### ISSUE TITLE
🦘 Sprungmarken funktionieren nicht

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/rrze-elements#190]
Details im verknüpften Issue in FAU Einrichtungen:
RRZE-Webteam/rrze-elements#193

**Comment by lukasniebler** [comment]
🎫 http://go.fau.de/9srj9

**Comment by cassandre** [comment]
Erledigt in 2bb7c3cbc2f12cbaf452519eca5f5f0bd257921b
