### ISSUE TITLE
Idee: Automatisches Inhaltsverzeichnis

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/rrze-elements#195]
Mal wieder eine Idee für ein zukünftiges Features:

Ein Shortcode z.B. [table_of_contents] erstellt eine umnummerierte oder nummerierte Liste anhand der h2..h3..h4 Überschriften auf der Seite und verlinkt sie anhand der vorher zugewiesenen IDs der Überschriftelemente.

**Comment by xwolfde** [comment]
Ich denke das ist durch den dafür aus dem Core kommenden Block im neuen Editor obsolet geworden.
