### ISSUE TITLE
👍 Feature request - Notices um zwei Daumen erweitern 👎

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/rrze-elements#199]
Vorweg:
Besonders Cool wäre es eigentlich, wenn man ähnlich wie bei den Accordeon-Icons diese auch für Notices nutzen kann. Ähnlich wie hier zu sehen:
<img width="850" alt="Bildschirmfoto 2022-06-08 um 14 52 33" src="https://user-images.githubusercontent.com/58593037/172621032-c6844099-4341-4c5c-8465-ccbc6875eb7c.png">
https://support.apple.com/de-de/guide/iphone/iph1fd7e482f/ios

( So hätte man eine ganze Palette an Icons, die man für bestimmte Paragraphen zur Hervorhebung nutzen kann. )

Für Anleitungsseiten wäre es praktisch, wenn es bei den Notices auch eine
<img width="850" alt="Bildschirmfoto 2022-06-08 um 14 50 01" src="https://user-images.githubusercontent.com/58593037/172620513-7945d512-f7b0-4c66-95c2-32b6d76cad68.png">

[notice-thumbs-up] oder alternativ [notice-correct] und ein
[notice-thumbs-down] oder alternativ [notice-false] etc. gibt.

Also einmal einen grünen Daumen nach oben und einen roten Daumen nach unten.

Schön sieht man das auch bei der Google Dokumentation, wo so Negativ- und Positivbeispiele hervorgehoben werden.

**Comment by cassandre** [comment]
Der erste Punkt sollte mit https://github.com/RRZE-Webteam/rrze-elements/commit/3ff222c38023d3f459f0dcf2319105ac2d419012 erledigt sein:
`[icon icon="exclamation-triangle" style="2x, pull-left" color="#FF1493"]`
Könnte man sogar in ein `[alert]...[/alert]` einbauen.
