### ISSUE TITLE
Verbesserte Benutzerinteraktion

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-elements#2]
Einige Verbesserungen, die unsere Kunden gerne umgesetzt sehen möchten:

* Wenn man einen collapse / ein accordion öffnet, springt die Ansicht nicht korrekt auf den angeklickten collapse bzw. den Beginn seines Inhalts um. Man landet irgendwo mittendrin oder am Fuß der Seite. Besonders störend in der mobilen Ansicht.
* Ein collapse mit load="open" schließt sich, sobald ein anderer collapse geöffnet wird (soweit ok). Schließt man diesen collapse wieder, sind alle collapses geschlossen. Es wäre jedoch wünschenswert, wenn der collapse mit load="open" dann wieder geöffnet dargestellt würde.

Kopie des Issues aus https://github.com/RRZE-Webteam/FAU-Einrichtungen/issues/432

**Comment by cassandre** [comment]
Ist irgendwann mal schon so umgesetzt worden. Bzw. Punkt 1 so umgesetzt, dass load="open" beim öffnen anderer Accordions nicht schließt.
