### ISSUE TITLE
Spaltenabstand

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/rrze-elements#201]
<img width="765" alt="image" src="https://user-images.githubusercontent.com/9526974/177946883-71d3d856-81e6-4e95-9260-d96e9307d36e.png">
Bei Spalten mit Alerts auf der einen Seite und Kalender/Text auf der anderen Seite wirkt der Abstand zwischen den Spalten sehr klein. Egal, ob mit  [columns] oder [two_columns_one] erstellt.
Beispiel: https://ibz.fau.de

**Comment by cassandre** [comment]
`#content .alert` hat 15px negativen margin-right und margin-left. Kommt aus FAU-Einrichtungen. Weiß der Geier, warum.

**Comment by wrcg** [comment]
<img width="581" alt="image" src="https://user-images.githubusercontent.com/9526974/179454490-761c84d6-ba85-4eb9-abeb-ed927bff5f4f.png">
gleich noch einmal ein "Abstandsproblem" bei der Kombi von [pull-left] und Zitat... (Beispiel: https://www.fau.eu/presidents-welcome-award/)

**Comment by cassandre** [comment]
@wrcg 
Das liegt am Custom CSS:
````
@media (min-width: 768px) {
	#content blockquote {
		position: static;
		padding-left: 0;
	}
}
````
Keine Ahnung, wozu das gut ist. Damit müsste das Problem auch bei normalen Zitaten ohne pull-div auftreten.

**Comment by cassandre** [comment]
Wegen der Alerts: Das war ein Tippfehler im CSS von FAU-Einrichtungen. Gefixt in [6895da41ad0e0f1e76b9f40c9bee898fccac51d9](https://github.com/RRZE-Webteam/FAU-Einrichtungen/commit/6895da41ad0e0f1e76b9f40c9bee898fccac51d9), sollte beim nächsten Theme-Update behoben sein.
