### ISSUE TITLE
🪲 Nicht alle Font-Awesome Icons funktionieren in Akkordeons

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/rrze-elements#202]
Von Kundenseite gab es den Wunsch, bestimmte fa-Icons zu nutzen.
Allerdings funktionieren bestimmte Icons nicht, obwohl Sie in v.4.7 aufgeführt werden.

https://fontawesome.com/v4/icons/

z.B. funktioniert user-circle nicht. Andere Icons mit Bindestrich funktionieren allerdings.

Weitere Details gibt es unter:
🎫 http://go.fau.de/9s7e-
💻 https://www.wordpress.rrze.fau.de/testseite-3/

**Comment by xwolfde** [comment]
Hm, ich bin mir nicht sicher, ob das gut ist.
Die FA Icons sind nun schon alt und die Technik wie sie verwendet werden (also Font) ist nicht mehr zeitgemäß.
Aus dem Theme werden die FA Icons daher auch nach und nach entfernt. 

Wenn das Plugin die aber noch liefert (tut es lt: https://github.com/RRZE-Webteam/rrze-elements/tree/master/assets/fonts/fontawesome) , dann sollten wir da schauen, wie wir das in Zukunft weiter betreuen wollen. Allerdings ist der Haken der, dass die Icons vom Plugin nur geladen werrden, wenn das Plugin über ein Shortcode in der jeweiligen Seite auch aktiv ist. Wenn es kein Shortcode zum Plugin gibt, würde auch dessen CSS nicht geladen werden und damit auch nicht der Font.
