### ISSUE TITLE
Highcharts integrieren

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-elements#204]
Wir haben noch ein eigenes Plugin RRZE Highcharts (https://gitlab.rrze.fau.de/rrze-webteam/rrze-highcharts) . 

Bitte prüfen, ob man diese Funktionalität nicht in RRZE Elements übernehmen könnte.

**Comment by lukasniebler** [comment]
In meinen Augen gehört Highcharts nicht ins Elements-Plugin.

In der Doku haben wir Elements bis jetzt immer als Gestaltungselemente für den Editor verkauft und nicht als Plugin für Datenvisualisierung.

Zur Zeit benutzen auf unserem CMS zwei Webseiten das Highcharts-Plugin. Da macht es mehr Sinn, wenn man sich in Zukunft Gedanken macht, ob man ein Plugin für Datenvisualisierung anbietet, dass dann schönere Graphen erstellen kann als den (nicht so schönen) Standard-Highcharts-Graph.

In Elements würde ich das nicht rein packen... Da passt Datenvisualisierung irgendwie nicht ins Thema.

Da macht es mehr Sinn, wenn die Funktionen aus dem Highcharts-Plugin irgendwann ins Statistik-Plugin wandern. (Dort wird Highcharts sowieso schon z.B. fürs Dashboard geladen).

**Comment by xwolfde** [comment]
Ok, ist plausibel. Dann lassen wir es mal so wie es ist.
