### ISSUE TITLE
Shortcode [pull-right]: Die Zeilenhöhe liegt unter dem Mindestwert 

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/rrze-elements#208]
Siteimprove gibt für Seiten mit [pull-right] einen Accessibility-Fehler an: Die line-height ist zu gering, sie müsste mindestens das 1,5-fache sein.

Beispiel: https://www.fau.de/outreach/wissenschaft-fuer-buergerinnen-und-buerger/wissen-wollen/

**Comment by cassandre** [comment]
Bin ich blind, oder ist auf der Seite gar kein pull-right? 
Ich kanns bei mir lokal auch nicht reproduzieren, da haben die pull-divs 1.5 line-height.

**Comment by AndiWebred** [comment]
Nee, du bist nicht blind, du hast nur nicht das Akkordeon geöffnet :D Anderes Beispiel ohne Accordeon wäre hier: https://www.fau.de/2021/07/frisch/mission-money/ (ich weiß, die pull-rights könnte man in diesem fall auch anders lösen)

**Comment by cassandre** [comment]
OK, ich weiß jetzt auch, warum bei mir lokal alles OK ist: Wurde in dev in https://github.com/RRZE-Webteam/rrze-elements/commit/eb769569d18b02c95f033d3cf4628077556f2973 schon gefixt. Ist also im Update heute oder morgen mit drin. :-)
