### ISSUE TITLE
Button "Alle öffnen" in Accordions dt./engl. Kuddelmuddel

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/rrze-elements#214]
In Accordions steht auf deutschen Seiten beim Button "Alle öffnen". Klickt man auf den Button, erscheint im Button der englische Text "Collapse All". Klickt man wieder drauf, dann erscheint im Button der Text "Expand All".

**Comment by itodnerd** [comment]
Spracheauflösung funktioniert nicht.
Zum einen fehlt der Eintrag für `__("Collapse All", "rrze-elements")`  in /languages/rrze-elements-de_DE.po.

Zudem scheint das Auflösen von `__("Expand All", "rrze-elements")` auch bei Existierendem Eintrag nicht zu funktionieren...
Workaround für das erste ExpandAll wurde in be28bf3adc5ffca96e904be4a7c6adff1f75ff9e durchgeführt

[Doku zur Verwendeten Funktion](https://developer.wordpress.org/reference/functions/__/)

**Comment by AndyFau** [comment]
Wir haben aktuell das selbe Problem unter: https://www.eei.tf.fau.de/department/auszeichnungen-und-ehrungen/
