### ISSUE TITLE
Seltsame Leerzeile bei manchen Accordeons

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/rrze-elements#215]
Bei manchen Accordeons tauchen zur Zeit immer mal wieder seltsame Leerzeilen auf. Die gehen meistens wieder weg, wenn man die Seite neu speichert, aber ich hab noch keine Regel gefunden, nach der diese Leerzeilen erscheinen, oder nicht.
Sieht so aus wie im Screenshot:
<img width="581" alt="2022-08-11 11_51_17-Sachgebiet Tierschutzangelegenheiten _ Friedrich-Alexander-Universität Erlangen-" src="https://user-images.githubusercontent.com/53909165/184108569-bf3c3f25-d923-43d7-a389-ca3564964a64.png">
https://www.fau.de/fau/leitung-und-gremien/gremien-und-beauftragte/beauftragte/sachgebiet-tierschutzangelegenheiten/#collapse_6

**Comment by cassandre** [comment]
Liegt an einer etwas zu allgemein gefassten CSS-Anweisung im FAU-Theme: 
`.admin-bar #content main :target { padding-top: 32px; }`

Werde ich dann im Plugin-CSS für das Accordion überschreiben.
