### ISSUE TITLE
🪲 Notices geben Icons doppelt aus

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/rrze-elements#218]
# Problem
Notices-Shortcode gibt alte Icons + Neue FA-Icons zeitgleich nebeneinander aus.
<img width="209" alt="Bildschirmfoto 2022-08-17 um 07 51 37" src="https://user-images.githubusercontent.com/58593037/185044462-3875c837-ae9a-4612-a32d-1954786b3cfd.png">

## Beispiele:
- https://www.wordpress.rrze.fau.de/plugins/inhaltsseiten-mit-funktionen-erweitern/elements/notices-absatzklassen/
- https://www.rrze.fau.de/hard-software/software/home-use/

## Verknüpfte Helpdesk-Fälle:
🎫 http://go.fau.de/9teyf

**Comment by cibsell** [comment]
Ich habe das auf der englischen Seite, auf der deutschen scheint es zu passen.

Allerdings werden auf beiden Seiten die Font-Awesome Icons nicht richtig ausgegeben, z. B. [icon icon="twitter"]. Auf eurer Wordpress-Seite ist der Bug auch.

**Comment by lukasniebler** [comment]
@cibsell 
Zu den Icons gab es leider nochmal eine Änderung. Und zwar muss man inzwischen die Icons aus Font Awesome 6 verwenden.

Da gibt es jetzt drei Icon-Sets...: Solid (das nimmt der Shortcode als Standard) | Regular | Brands

Für Twitter müsstet du dann quasi [icon icon="brands twitter"] schreiben. Da hängt die Dokumentation leider noch etwas hinterher.

Also: [icon icon="brands twitter"] zum Beispiel.

Hier ist der Link zu den neuen FA6 Icons:
https://fontawesome.com/search?m=free&s=solid%2Cregular%2Cbrands
