### ISSUE TITLE
Alert in Alert?

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/rrze-elements#235]
Wäre es möglich einen doppelten Alert zu setzen? Also ein Kasten im Kasten.
Zum Beispiel hätte man außen einen Kasten mit weißer Fläche und schwarzem Rand und innen drei farbige Alerts.

**Comment by cassandre** [comment]
Man kann keine Shortcodes mit Schluss-Tag (`[/...]`) mit demselben Namen ineinander verschachteln. WP interpretiert den ersten schließenden Tag als schließender Tag des ersten öffnenden Tags. Daher wird es einen Workaround mit dem Shortcode `inner_alert` geben (der ansonsten genauso funktioniert wie der Alert:

`````````
[alert color="#ffffff" border_color="#000000"]

[columns number="3"]

[column]
[inner_alert style="info"]
Das ist ein erster Alert in einer Column in einem Alert.
[/inner_alert]
[/column]

[column]
[inner_alert style="success"]
Das ist ein zweiter Alert in einer Column in einem Alert.
[/inner_alert]
[/column]

[column]
[inner_alert style="danger"]
Das ist ein dritter Alert in einer Column in einem Alert.
[/inner_alert]
[/column]

[/columns]

[/alert]
`````````

<img width="752" alt="Bildschirmfoto 2022-11-02 um 15 17 08" src="https://user-images.githubusercontent.com/4435815/199513195-3d3775fb-0a74-46ea-a0c0-e81c0137f8ab.png">

**Comment by cassandre** [comment]
Alternativ könnte man auch dem Columns-Shortcode eine Hintergrund- und Randfarbe geben?
