### ISSUE TITLE
Blockquote: unterschiedliches padding auf fau.de und fau.eu

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/rrze-elements#237]
Auf fau.de und fau.eu gibt es ein unterschiedliches Padding bei den blockquotes:
https://www.fau.eu/2022/09/16/news/research/measuring-research-performance-do-only-numbers-count/
https://www.fau.de/2022/09/news/wissenschaft/wissenschaftliche-leistung-zaehlen-nur-die-zahlen/

**Comment by cassandre** [comment]
Hat nix mit Elements zu tun – die Blockquotes werden im Theme definiert. Allerdings war auf der englischen Seite Custom CSS eingetragen, das den padding links entfernt. Ich vermute, das geht noch auf das alte FAU-Theme zurück, das vor dem Zitat ein großes Anführungszeichen stehen hatte, das damit ausgeblendet werden sollte. 

Ich hab das CSS mal entfernt – passt wieder.
