### ISSUE TITLE
hide="thumbnail" scheint nicht in Custom News zu funktionieren

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/rrze-elements#241]
Die Funktion hide="thumbnail" funktioniert anscheinend nicht im Shortcode [custom-news]

[custom-news hide="thumbnail"]

**Comment by cassandre** [comment]
`hide="thumbnail"` funktioniert nur in nicht-FAU-Themes (FAU-Events, RRZE...). Bei den FAU-Themes verwendet der Shortcode die dortige Funktion `fau_display_news_teaser($id = 0, $withdate = false, $hstart = 2, $hidemeta = true) {...}`, die das nicht vorsieht. Hier wird die Anzeige der Thumbnails über die Customizer-Option gesteuert.
