### ISSUE TITLE
Bildlinks können in Menüs nicht mehr hinzugefügt werden

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/rrze-elements#275]
Die frühere Option bei Menüs einen Bildlink auszuwählen, ist weg...
<img width="654" alt="image" src="https://github.com/RRZE-Webteam/rrze-elements/assets/9526974/95f79aa2-c04a-4c67-950a-6f212721dacd">

**Comment by xwolfde** [comment]
Ja. Ist bekannt. Teil des Themes:
https://github.com/RRZE-Webteam/FAU-Einrichtungen/issues/1344
