### ISSUE TITLE
Tabs: Sind Tabs mit Tastatur anwählbar?

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/rrze-elements#283]
Siteimprove hat mich draufgebracht: Die einzelnen Tabs sind soweit ich das feststellen kann nicht mit der Tastatur anwählbar. Oder übersehe ich da etwas?
Beispiel: https://www.fau.de/fau/kontakt-anfahrt-orientierung/

**Comment by cassandre** [comment]
Sind anwählbar, aber der Fokus ist nicht ausreichend erkennbar.
