### ISSUE TITLE
Merken eines geöffneten Accordions

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-elements#3]
"Wunsch: Wenn man aus dem Accordion heraus einen Link anklickt und anschließend wieder mit dem Browser-Zurück-Button auf die Ursprungsseite geht, wäre es schön, wenn das vorher angesprochene Accordion noch geöffnet wäre."

Problem: Wenn wir das mit Cookies oder Broeserstore "merken" lassen, wären wir gezwungen die EU Richtline zu Cookies anzuwenden und einen Cookie-Hinweis auf allen Seiten zu werfen. Das wollen wir nicht!
Ist irgendeine andere Lösung denkbar?

**Comment by cassandre** [comment]
Geht mit JS: window.history.pushState()
