### ISSUE TITLE
Accordion-Farben

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/rrze-elements#301]
Wenn ich in einem Accordion  expand-all-link="true" weglasse oder expand-all-link="" schreibe, erscheint der jeweilige Balken einfarbig in dunkelgrün statt wie bisher vorne einen schmalen Balken in Fakultätsfarben und grau, siehe:

Ohne expand-all-link="true":

![Screenshot 2023-09-13 at 09-20-56 Studiengänge - FAU Naturwissenschaftliche Fakultät](https://github.com/RRZE-Webteam/rrze-elements/assets/8234890/fd4b6c24-ddd7-4cea-b08f-2568b04b47b4)

Mit expand-all-link="true":

![Screenshot 2023-09-13 at 09-20-40 Studiengänge - FAU Naturwissenschaftliche Fakultät](https://github.com/RRZE-Webteam/rrze-elements/assets/8234890/205e6bd6-7852-44e4-b23c-01abd1772be2)

Ist das richtig so? Soll das so sein?

**Comment by cassandre** [comment]
Nein, das soll nicht so sein. Es ist ein Rest des wpautop-Bugs, der uns seit einer Weile beschäftigt. Wenn man die einzelnen Shortcodes in einzelne Absätze (nicht nur einfacher Zeilenumbruch) macht, funktioniert es auch ohne expand-all-link. 
Wir werden trotzdem schauen, dass wir das gefixt bekommen.

**Comment by cassandre** [comment]
in 1.25.19 gefixt
