### ISSUE TITLE
Alte Shortcodes

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-elements#31]
Bitte zur Abwärtscompatibilität die alten Shortcodes mit einbauen:

```                // Old Shortcodes for downwards compatibility
                add_shortcode('alert', array( $this, 'absatzklasse_attention' ));
                add_shortcode('attention', array( $this, 'absatzklasse_attention' ));
                add_shortcode('hinweis', array( $this, 'absatzklasse_hinweis' ));
                add_shortcode('baustelle', array( $this, 'absatzklasse_baustelle' ));
                add_shortcode('plus', array( $this, 'absatzklasse_plus' ));
                add_shortcode('minus', array( $this, 'absatzklasse_minus' ));
                add_shortcode('question', array( $this, 'absatzklasse_question' ));
```

**Comment by cassandre** [comment]
Diese Shortcodes stehen schon in FAU-Einrichtungen mit dem Kommentar `"Old Shortcodes for downwards compatibility"`, und zwar seit 01.08.2016 (
https://github.com/RRZE-Webteam/FAU-Einrichtungen/commit/a3b5486f962d0142d12c98b887c9f5e4ad3738b). Daher hatte ich sie eigentlich absichtlich rausgelassen. 
Wenn es Altlasten sind, wie lange willst du sie mitschleifen? 
Oder nehmen wir sie wieder als normale Alternative mit rein (fände ich allerdings zu verwirrend)?
