### ISSUE TITLE
Accordion-Pfeil

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/rrze-elements#310]
bei farbigen Accordionbalken ist der Pfeil beim Hovern nicht komplett weiß (betrifft alle Farben außer rot und blau):
![image](https://github.com/RRZE-Webteam/rrze-elements/assets/9526974/e9b5cc74-ca60-4d8e-ad9c-ca134b984bfc)

**Comment by cassandre** [comment]
fixed in https://github.com/RRZE-Webteam/rrze-elements/commit/9e65203a332f24f6046764215290a07834e3d396
