### ISSUE TITLE
Bilder im Text // Accordion

### ISSUE THREAD

**Issue by mduven** [RRZE-Webteam/rrze-elements#32]
Habe mit dem neue Accordion auf einer Seite (https://www.innovationspreis.wiso.rw.fau.de/fachbereich/) das Problem, dass sich diese neben Bildern nach unten verschieben. War vorher nicht so:

![2018-10-09 14_14_20-fachbereich wiso-innovationspreis](https://user-images.githubusercontent.com/28564104/46669429-b4fdc980-cbcf-11e8-96b4-cef3a58fd5c5.png)

**Comment by cassandre** [comment]
Oh, das war eine Altlast aus dem FAU-Theme. Sollte jetzt behoben sein. Danke für den Hinweis.

**Comment by mduven** [comment]
Bin gerade erst dazugekommen.. Das Problem besteht leider noch immer..

**Comment by cassandre** [comment]
Ich kann es leider nicht reproduzieren: Hier werden die Accordions normal angezeigt. Darf ich es mal auf Ihrer Seite probieren?
![bildschirmfoto 2018-10-18 um 17 23 00](https://user-images.githubusercontent.com/4435815/47165665-c4c98c00-d2fa-11e8-8055-70743b8cfaef.png)

**Comment by mduven** [comment]
Hab die Accordions nochmal eingebaut, sieht sowohl im Friefox als auch im Chrome wie oben aus. Ist mir auch schon auf mehreren fau.de-Seiten aufgefallen, z.B. https://www.fau.de/patente-gruendung-wissenstransfer/gruenden/service-fuer-gruender/

**Comment by cassandre** [comment]
Sorry, es gab ein Problem mit dem Update. Müsste jetzt funktionieren.

**Comment by mduven** [comment]
Hm also auf der fau.de-Seite sieht es nun besser aus, bei uns leider nicht.. Hab versucht das hin und her zu schieben, leider erfolglos..

**Comment by cassandre** [comment]
Sicher, dass das Plugin bei Ihnen aktiviert ist?
Ich sehe im Quellcode auf Ihrer Seite kein RRZE-Elements-Style-Sheet.

**Comment by mduven** [comment]
ah das war die lösung. war mir so nicht klar, aber gut zu wissen.

**Comment by cassandre** [comment]
Sicher, dass das Plugin bei Ihnen aktiviert ist?
Ich sehe im Quellcode auf Ihrer Seite kein RRZE-Elements-Style-Sheet.


Am 22.10.2018 um 15:38 schrieb mduven <notifications@github.com<mailto:notifications@github.com>>:


Hm also auf der fau.de<http://fau.de>-Seite sieht es nun besser aus, bei uns leider nicht.. Hab versucht das hin und her zu schieben, leider erfolglos..
