### ISSUE TITLE
Möglichkeit Sprungmarken (Inhaltsverzeichnis) zu erstellen

### ISSUE THREAD

**Issue by Erik-2007** [RRZE-Webteam/rrze-elements#321]
Um ein Inhaltsverzeichnis (Innerhalb der Seite soll auf gewünschte Content-Elemente verlinkt werden können) auf einer Seite anlegen zu können, benötigen wir die Möglichkeit Sprungmarken zu erstellen.
Wenn ich es richtig sehe, erzeugen die derzeitigen Content-Elemente nicht automatisch eine eigene ID. Bei Gutenberg ist das aber der Fall. 
Spätestens bei der Umstellung auf Gutenberg wäre es toll, wenn man auf diese IDs innerhalb einer Seite verlinken könnte.

**Comment by xwolfde** [comment]
Mit Gutenberg wird es einen eigenen Block für die seitenspezifischen Inhaltsverzeichnisse geben. Das ist bereits eine Core-Funktion und muss daher nicht neu gebaut werden.

Eine herkömmliche Sprungmarke ist ein normaler Link ohne href, aber mit name-Attribut.

**Comment by Erik-2007** [comment]
Welcher Block ist das denn? Kann es sein, dass er im Francesca-Theme nicht vorhanden ist? 
Aktuell haben wir dann aber definitiv keine Möglichkeiten, Sprungmarken zu setzen, oder?

**Comment by Erik-2007** [comment]
Sorry, hat sich erledigt. Habe herausgefunden, wie es funktioniert. Ich close diesen Issue mal unauffällig :).

**Comment by Erik-2007** [comment]
siehe oben
