### ISSUE TITLE
Pfeile bei Text-Slider fehlt

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/rrze-elements#329]
![image](https://github.com/RRZE-Webteam/FAU-Einrichtungen/assets/9526974/d9833f12-de00-4c33-897d-01b5c39db812)
Beispiel: https://www.fau.de/fau/standorte-der-fau/fau-campus-erlangen/

**Comment by xwolfde** [comment]
Der Textslider kommt aus dem Elements-Plugin => Verschiebe es dahin.

**Comment by xwolfde** [comment]
(HIntergrund: Das Theme läd kein Awesome Font mehr. Hier müsste das Elements-Plugin den Font laden, wenn es die Pfeile damit machen will)

**Comment by cassandre** [comment]
fixed in https://github.com/RRZE-Webteam/rrze-elements/commit/9e65203a332f24f6046764215290a07834e3d396
