### ISSUE TITLE
Shortcode um Links mit Sprachflaggen kennzeichnen

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-elements#34]
Wir haben hier einen Issue um Links mit einem SPrachcode zu kennzeichnen: 
https://github.com/RRZE-Webteam/FAU-Einrichtungen/issues/198

Im Prinzip geht es also um die Einführung von neuen Shortcodes derart:

[symbol type="flag" value="en"] zeigt eine englische Flagge (Britisch)
[symbol type="flag" value="de"] zeigt eine deutsche Flagge
[symbol type="flag" value="int"] zeigt das neue internationale Sprachsymbol

Wäre das was für Elements?

**Comment by cassandre** [comment]
Wenn es sich nur um Links handelt, wäre es da nicht sinnvoller, einfach das Link-Bearbeiten-Popup um ein Textfeld für eine CSS-Klasse zu erweitern? Das gibt es bei Bildern und Menüpunkten ja auch.
