### ISSUE TITLE
Beim öffnen und schließen von Accordions wird der Buttontext nicht übersetzt

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/rrze-elements#352]
Beim öffnen und schließen des Accordions wird der Expand-All-Button nicht übersetzt.

**Comment by lukasniebler** [comment]
@cassandre 

Ich war mir nicht ganz sicher, ob die folgende Zeile so richtig ist. Vorher wurde Self:console_log aufgerufen. Vermutlich müsste man eine der Zeilen noch rausnehmen und den Befehl ```wp i18n make-json languages/ --no-purge```nochmal laufen lassen? (Es wurden 2 statt 1 json erstellt...)

https://github.com/RRZE-Webteam/rrze-elements/commit/6a17470cb174b72fe304816438bf1eb997d9941c#diff-9315431d3e16a959b7f0e9aa10fa34f7459f90e37d66a7009dfbceba24c5dc5cR194

**Comment by cassandre** [comment]
Duplikat zu #214
