### ISSUE TITLE
Absatzklassen/Shortcodes Fakultätstheme - Farben vergessen?

### ISSUE THREAD

**Issue by Albager** [RRZE-Webteam/rrze-elements#36]
Neuerdings erscheinen die Absatzklassen nicht mehr in den Fakultätsfarben (wäre bei uns das NatFak-grün), sondern alle blau (vgl. https://www.geographie.nat.fau.de/shortcodes/):

![image](https://user-images.githubusercontent.com/11389126/47998313-27929400-e0ff-11e8-871c-9f559703d887.png)

Is it a bug or a feature?

**Comment by cassandre** [comment]
Erledigt in https://github.com/RRZE-Webteam/rrze-elements/commit/6971e1e6be994bf8db4c4dc3041149c559ca16c9.
