### ISSUE TITLE
Erster Absatz in Accordions ohne Abstand

### ISSUE THREAD

**Issue by endv02** [RRZE-Webteam/rrze-elements#37]
Bei Absätzen in Accordions wird zwischen erstem und zweitem Absatz kein Abstand eingefügt, weil <p></p> beim ersten Absatz fehlt:
<div class="accordion-inner clearfix">Hier der Text
<p>Und nochmal ein zweiter Absatz</p>
<p>Und ein dritter Absatz</p></div>
Ausgabe siehe https://www.beta.wordpress.rrze.fau.de/theme-shortcodes/accordions/#sprungmarke2 (bei Standard Accordion)

**Comment by cassandre** [comment]
Ist gefixt. Allerdings muss im Editor auch ein echter Absatz eingefügt werden, nicht nur ein Zeilenumbruch.

**Comment by endv02** [comment]
Mit dem neuen Theme scheint das Problem wieder zu bestehen...

**Comment by cassandre** [comment]
Nagut, dann eben mit Gewalt: https://github.com/RRZE-Webteam/rrze-elements/commit/c855855dbde81f3fa6fa86c6f5b1a111488ac01b
