### ISSUE TITLE
Hinweis-Icons sind zu weit links gerückt

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/rrze-elements#39]
siehe: ![image](https://user-images.githubusercontent.com/9526974/48886910-dcca8900-ee2d-11e8-93ea-e5b80b21e80d.png)
![image](https://user-images.githubusercontent.com/9526974/48886937-ea800e80-ee2d-11e8-91d9-51f58d4b382e.png)
auch mobil...

**Comment by cassandre** [comment]
Ein Konflikt mit alten Styles aus dem FAU-Theme. Ein Quickfix ist eingespielt, sollte jetzt wieder normal aussehen. Nachhaltige Behebung im nächsten Theme-Update.
