### ISSUE TITLE
Sprungmarke auf accordion innerhalb einer Seite

### ISSUE THREAD

**Issue by Albager** [RRZE-Webteam/rrze-elements#4]
Wenn im Inhalt einer Seite auf ein Accordion auf der selben Seite verlinkt wird (href="#collapseXY") springt die Ansicht nicht korrekt um. Hängt vermutlich mit dem bestehenden Accordion-Sprung-Problem zusammen. Vgl. Der Link zu "Projekte" im Einleitungsteil von https://geographie.cms.rrze.uni-erlangen.de/person/markus-neufeld/ (die Ansicht springt immer ganz nach oben). 

Edit: Es funktioniert auch nicht, wenn man bspw. an ein html-tag innerhalb eines accordions eine id vergibt, auf die man im Link oben referenziert mit href="#projekte" (es passiert gar nichts).

Verlinkt man jedoch von einer anderen Seite auf ein accordion, funktioniert alles wie gewünscht und das angesteuerte accordion öffnet sich sogar gleich (z. B. von https://geographie.cms.rrze.uni-erlangen.de/studium/faq/#collapse_16 auf https://geographie.cms.rrze.uni-erlangen.de/person/bibliothek/#collapse_5).

edit: siehe auch [FAU-Einrichtungen Issue No. #480](../../FAU-Einrichtungen/issues/480#issuecomment-374148588)

**Comment by cassandre** [comment]
Funktioniert mittlerweile (Plugin rrze-elements muss allerdings aktiviert sein).
