### ISSUE TITLE
Ausblenden von Textteilen (Absätzen)

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/rrze-elements#43]
Nachdem HTML-Kommentare in unseren Themes nicht möglich sind, wäre es günstig, einen Shortcode zu haben, mit dem man Textteile bzw. Absätze temporär ausblenden kann (beispielsweise die Öffnungszeiten eines Sekretariats während des Semesters/während der vorlesungsfreien Zeit). Nachdem dazu eine Kundenanfrage vorliegt, gebe ich das als Issue weiter.
Das OTRS-Ticket findet sich unter https://www.helpdesk.rrze.fau.de/otrs/index.pl?Action=AgentTicketZoom;TicketID=688400

**Comment by cassandre** [comment]
In https://github.com/RRZE-Webteam/rrze-elements/commit/8169e17576e61fa9bfdb0b29c78fc68462df2afb erledigt:
Shortcode: [hidden-text]...[/hidden-text]
Optionale Parameter: start="Y-m-d H:i:s" end="Y-m-d H:i:s" (nur "Y-m-d" funktioniert auch).
