### ISSUE TITLE
Fakultätsfarben sind weg

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/rrze-elements#45]
Hallo,

nachdem es keinerlei Hinweis gab, dass der Shortcode "Hinweis" nicht mehr ging (ging zuvor problemlos und auch im NAT-grün), habe ich das Plugin rrze-elements (wieder?) aktiviert. Nun erscheint der Hinweis aber nur im FAU-blau. Wie kann ich wieder grün einstellen?

**Comment by xwolfde** [comment]
Huch? 
Hast du mal ne URL mit Beispieleinsatz?

**Comment by cibsell** [comment]
https://www.nat.fau.de/schule/schueler/schuelerpraktika/

**Comment by endv02** [comment]
Die Hinweistexte lagen früher im Theme und sind jetzt in das themeübergreifende Plugin rrze-elements gewandert. Vermutlich wurde vorher einfach die default-Farbe des Themes übernommen, das ist im Plugin aber (da absolut themeabhängig) aktuell nicht eingebaut, d.h. da müssen wir die Option der Fakultätsfarben bei Bedarf erst noch ergänzen.

**Comment by cibsell** [comment]
Der Bedarf ist da...

**Comment by xwolfde** [comment]
Damit das Plugin (bzw. dessen CSSS) weiß in welchen Theme es ist (und daher welche Defaultfarben vorliegen), werde ich das Theme mal um eine body class mit dem Themenamen ergänzen.

Also `<body class=" fau-einrichtungen ">`  bzw. `<body class=" fau-natfak ">`  etc.

Ausserdem schau ich mal, ob ich auf der STelle ein overwrite vom Theme im CSS eintragen kann.

**Comment by xwolfde** [comment]
faculty-$name

mit $name = nat, zuv, phil, tf, rw, med

**Comment by xwolfde** [comment]
Im nächsten Update gefixt
