### ISSUE TITLE
Schachteln von collapsibles und collumns

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/rrze-elements#49]
Kundenanfrage: Nach dem Aktivieren des Plugins sind alle Accordionfächer geöffnet und das Spaltenraster geht verloren (siehe: https://www.wtm.tf.fau.eu/lehrstuhl/team/). Ohne Elements geht das problemlos: https://www.wtm.tf.fau.de/lehrstuhl/team/. Das sollte möglichst bald behoben werden. 

Siehe auch https://www.helpdesk.rrze.fau.de/otrs/index.pl?Action=AgentTicketZoom;TicketID=693171.

**Comment by endv02** [comment]
Da kam ein Bug mit einem Bugfix rein, ist jetzt behoben.
