### ISSUE TITLE
Timeline // Text angeschnitten

### ISSUE THREAD

**Issue by mduven** [RRZE-Webteam/rrze-elements#54]
Im Event-Theme wird mir in der Timeline der Text seltsam angeschnitten angezeigt, finden das etwas irritierend:

![2019-02-11 15_04_46-historie 100 jahre handelshochschule nurnberg](https://user-images.githubusercontent.com/28564104/52568261-88242200-2e0e-11e9-8ca3-d57db47b3635.png)

Habe auf der Dokuseite der Plugins das gleiche Phänomen:
![2019-02-11 15_05_02-timeline die wordpress-themes fur fakultaten lehrstuhle und einrichtungen](https://user-images.githubusercontent.com/28564104/52568282-9a9e5b80-2e0e-11e9-96b0-24a0485a13f2.png)

Bei Klick auf den Pfeil springt der Strahl jeweils eine komplette Stelle weiter. Kann man das irgendwie beeinflussen?

**Comment by BastianMelsheimer** [comment]
Wir würden auch gerne die Timeline einsetzen, es scheint aber das oben beschriebene Problem vor allem auch bei eingeblendeten Menüs zu geben.

Die Pfeile links / rechts tun in diesem Fall leider gar nichts:

https://www.fau.de/schulung/bm/?preview_id=2235085

Der Link sollte noch ein paar Tage zugänglich sein.
