### ISSUE TITLE
Content-Slider in Sidebar: Zeilenumbruch bei jedem Wort (FAU-Themes)

### ISSUE THREAD

**Issue by chem455** [RRZE-Webteam/rrze-elements#57]
Wie mir gerade auffällt, wird nach dem letzten Update der Text im Slider nach jedem Wort umgebrochen, was die Lesbarkeit nicht gerade fördert.

<img width="312" alt="Bildschirmfoto 2019-04-25 um 09 24 14" src="https://user-images.githubusercontent.com/13415789/56717206-74653800-673c-11e9-807a-f1cab61445ae.png">

**Comment by cassandre** [comment]
Die Startseiten-Sidebar hatte ich beim testen nicht auf dem Schirm. Sollte jetzt aber passen.
