### ISSUE TITLE
Screenreader vs. accordion

### ISSUE THREAD

**Issue by Albager** [RRZE-Webteam/rrze-elements#6]
Ist hier schon aufgefallen, dass die accordions sich mit einem Screenreader nur sehr schlecht bzw. eigentlich gar nicht praktikabel durchnavigieren lassen? 

Wenn man sich beispielsweise auf der Seite https://geographie.cms.rrze.uni-erlangen.de/studium/faq/ den collapse https://geographie.cms.rrze.uni-erlangen.de/studium/faq/#collapse_29 vorlesen lassen will, muss man erst alle Menüpunkte vorlesen lassen (oder entsprechend lang und ungenau "vorskippen"), um zum gewünschten Inhalt zu gelangen - und damit der vorgelesen wird, muss der collapse aufgeklappt sein. Und wenn man dann einen anderen Punkt lesen möchte, geht das Spiel von vorne los... 
Oder stelle ich nur irgendwas falsch an?
(getestet mit Chrome und dem Read Aloud: A Text to Speech Voice Reader-Addon (https://chrome.google.com/webstore/detail/read-aloud-a-text-to-spee/hdhinadidafjejdhmfkjgnolgimiaplp?utm_source=chrome-app-launcher-info-dialog) unter Win10).

**Comment by xwolfde** [comment]
Ja, das und noch andere Sachen. Wir haben dazu auch seit kurzem Testergebnisse eine Prüferin. Hatte noch keine Zeit es als Issue aufzunehmen.

**Comment by cassandre** [comment]
Sollte sich durch den Umbau auf Buttons erledigt haben.
