### ISSUE TITLE
Galerie- bzw. Bild+Text-Slider

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-elements#7]
Aktuell wird die Galerie-Funktion vom Theme bereitgestellt.
Diese könnte auch in rrze-elements übergehen.

Zusätzlich wäre aber auch eine Erweiterung in der Form sinnvoll, daß hie rein Slider bestehend aus Text+Bild (jeweils optional Bild und optional Text) in der optischen Form angeboten wird, wie sie hier
aufbereitet wurde:
![2018-03-15-10-22-informatik-studium cms rrze uni-erlangen de](https://user-images.githubusercontent.com/1070669/37454504-14cd9806-283b-11e8-8f5d-e0f5fef75644.png)

Bei der Informatik bedient man sich momentan einer Grafik, in der die ganze Schrift enthalten ist. Dies ist aber für die Erstellung der Slides nicht bedienerfreundlich und es ist nicht barrierefrei.

**Comment by cassandre** [comment]
Da könnte man den Content-Slider aus dem Events-Theme übernehmen: http://www.test.rrze.uni-erlangen.de:2175/content-slider/

**Comment by xwolfde** [comment]
Ah... ja. Uns fehlt also eine DOku ;)

**Comment by cassandre** [comment]
In https://github.com/RRZE-Webteam/rrze-elements/commit/110b8080a578d5c811373447e55077d81510afe9 eingefügt.
