### ISSUE TITLE
Bild neben Text in [alert]

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/rrze-elements#71]
wenn in einem alert ein kurzer Text mit einem Bild erscheinen soll, wird das alert/die Hintergrundfarbe nach der Größe des Textes gewählt und nicht auch nach der Größe des Bildes. D.h. das Bild/die BU rutscht aus dem alert heraus.
![image](https://user-images.githubusercontent.com/9526974/64948075-9049b180-d876-11e9-942b-df73c9ba8265.png)

**Comment by xwolfde** [comment]
Ihr verwendet Alerts um die Hintergrundfarbe eines Bereiches zu ändern?
Äh... what?

Dir ist aber schon bekannt, dass in einem Alert auch semantische Markierungen Mitteilungen an z.B. Screenreader etc stecken und daher dieses KEINESFALLS für optische Zwecke missbraucht werden darf? Bitte das nicht machen.

Wenn ihr farbige Hintergrundflächen braucht, die nur optische Relevanz haben, dann können wir dafür gern was machen. Z.B. in Zusammenhang mit den Spalten-Shortcodes oder an anderen stellen.
Aber bitte bitte nicht einfach irgendwelche Dinge, für etwas anderes verwenden, nur weil es auf einem Browser unter einer gewissen Auflösung die Optik hat, die ihr gerade woanders nutzen wollte..
Genau das Problem fällt uns gerade bei den Galerien auf die Füße, die nicht als Galerie sondern als Download-Liste verwendet wurden...

**Comment by wrcg** [comment]
ja, das verwenden wir dafür, aus Mangel an Alternativen und sind eigentlich sehr froh, dass es dies gibt ;-) Was ist denn  genau der Unterschied zwischen dem alert und einer farbigen Hintergrundfläche...?

**Comment by xwolfde** [comment]
Das eine ist rein dekorativ und hat dabei keine Auswirkungen auf Screenreader und co.

Bei den Alerts sollen aber auch ARIA-Roles angegeben werden (noch nicht umgesetzt, aber als Issue schon vorhanden), die einem Screenreader oder auch anderen UserAgents und Bots darauf hinweisen, dass dieser Bereich von höherer Relevanz ist als anderer Text auf der Website.

Wir sollten (müssen) diese beiden Dinge also rein semantisch trennen.
Optisch mag beides gleich aussehen, Semantisch ist es aber unterschiedlich.

**Comment by xwolfde** [comment]
(Nebenbei fällt mir am obigen SCreenshot auch auf, dass wir uns eine Lösung wegen Bilder dann überlegen müssen. Bei Nutzung der hellgrauen Hintergrundfarbe würde die ebenfalls nur schwach dunkle Schrift der Bildcaption nicht mehr genug Kontrast haben.)
