### ISSUE TITLE
Ausdrucken von Seiten mit Accordeons nicht möglich

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/rrze-elements#75]
Fehlerbeschreibung: 

Seiten mit Akkordeons nicht ausdruckbar. Verwendeter Browser Firefox (evtl. auch bei anderen Browsern vorhanden).
Beim versuch Seiten zu Drucken wird das Akkordeon einfach abgeschnitten bei Seitenende.

Beispielseite:
https://www.rrze.fau.de/infocenter/preise-kosten/

[Apple_macOS_und_iOS___Regionales_Rechenzentrum_Erlangen__RRZE_.pdf](https://github.com/RRZE-Webteam/rrze-elements/files/3949596/Apple_macOS_und_iOS___Regionales_Rechenzentrum_Erlangen__RRZE_.pdf)
[Karriere___Regionales_Rechenzentrum_Erlangen__RRZE_.pdf](https://github.com/RRZE-Webteam/rrze-elements/files/3949597/Karriere___Regionales_Rechenzentrum_Erlangen__RRZE_.pdf)

**Comment by xwolfde** [comment]
Wenn media printer, dann sollten generell alle Accordions offen sein (und entsprechende Buttons wie Open All sollten nicht mehr sichtbar sein)

**Comment by cassandre** [comment]
Print-Style in https://github.com/RRZE-Webteam/rrze-elements/commit/bb9d0658a79aac97274c7a818bedf31374d8c5e1 verbessert. Dass die Accordions abgeschnitten werden, ist allerdings ein Firefox-Problem, das ich nicht beheben kann. Ausdruck in anderen Browsern (Chrome, Safari, Opera) funktioniert. 

Die allgemeinen Print-Styles des RRZE-Themes werden noch überarbeitet.
