### ISSUE TITLE
Timeline-Darstellung funktioniert nicht korrekt bei zu wenig Text

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/rrze-elements#76]
Wenn bei Timeline-Elementen nur eine Überschrift, jedoch kein dazugehöriger Text eingegeben wird, wird die Timeline falsch dargestellt.

[timeline]
[timeline-item name="test"]
<h1>Überschrift1</h1>
[/timeline-item]
[timeline-item name="test2"]
<h1>Überschrift2</h1>
[/timeline-item]
[timeline-item name="test3"]
<h1>Überschrift3</h1>
[/timeline-item]
[/timeline]

**Comment by Blubbaa** [comment]
Genau den selben Fall hatte ich auch gerade, nur dass auch mit eingegebenem Text auftritt. Nach etwas ausprobieren, denke ich die Timeline wird nur korrekt dargestellt, wenn das erste Item mindestens einen automatischen Zeilenumbruch im Text erzeugt.

```
[timeline]
[timeline-item name="test1"]
<h1>Überschrift 1</h1>
Zu wenig Text.
[/timeline-item]
[timeline-item name="test2"]
<h1>Überschrift 2</h1>
Hier ist es egal wie viel Text.
[/timeline-item]
[/timeline]
```

**Beispielbilder:**
![image](https://user-images.githubusercontent.com/10139960/72155748-1359bf00-33b4-11ea-95d0-5112ecd8b65e.png)

![image](https://user-images.githubusercontent.com/10139960/72155788-31272400-33b4-11ea-8747-46fe9ead09c4.png)
