### ISSUE TITLE
Bildgallerien laden innerhalb von geschlossenen Akkordion-Tabs nicht

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/rrze-elements#78]
Eingefügte Gallerien laden nur im gerade geöffneten Abschnitt eines Akkordions. Wenn man Gallerie im Akkordion sehen möchte muss man erst Akkordionabschnitt öffnen und Seite aktualisieren. 
![grafik](https://user-images.githubusercontent.com/58593037/73733644-9fa19c80-473c-11ea-90d6-2b6f360b55e4.png)

Beispielseite:
https://www.wordpress.rrze.fau.de/2017/02/22/neue-homepage-mit-wordpress/
(Tritt auf bei öffnen mit Firefox / Edge)

**Comment by cassandre** [comment]
Das scheint ein Problem mit der Galerie des FAU-Themes zu sein. Die Standard-WP-Galerien funktionieren .
