### ISSUE TITLE
Timeslider mit Lightbox bei Bilder

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-elements#8]
Bei dem Zeitstrahl wäre es günstig, wenn man beim Klick auf ein Bild eine Lightbox erhielt, statt auf die Bildurl umgeleitet zu werden

**Comment by cassandre** [comment]
Ab https://github.com/RRZE-Webteam/rrze-elements/commit/a14afb94f6702a16e9fed4b16b9f015aff383e83 ist die lightbox Teil von Elements. Funktioniert überall, nicht nur in der Timeline, indem man dem Link die Klasse "lightbox" gibt.
