### ISSUE TITLE
Open All bei Accordions funktioniert nur bei erster Accordiongruppe

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-elements#84]
Sind mehr als eine Accordion-Gruppe auf einer Seite, die alle mit dem Open All Argument ausgestattet sind, funktioniert nur der KLick auf den ersten Button.

**Comment by cassandre** [comment]
Kann ich nicht reproduzieren. Mit Fau-Einrichtungen und RRZE-2019 getestet
