### ISSUE TITLE
News-Slider aus Beiträgen

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-elements#85]
Könnten wir mit Elements einen Nachrichtenslider wie dem auf ZDF machen:

![ZDF-newsslider-20200318](https://user-images.githubusercontent.com/1070669/76994189-ef7fa000-6945-11ea-9753-b4b022a5af84.png)

**Comment by cassandre** [comment]
Lässt sich machen. Ist eigentlich nur eine Mischung aus der Technik des Bildlink-Slider aus FAU-Einrichtungen und dem Inhalt des [Content-Slider](https://www.wordpress.rrze.fau.de/plugins/fau-und-rrze-plugins/elements/content-slider/).
