### ISSUE TITLE
Sprungmarke funktioniert nicht - Attribut "name" wird ignoriert

### ISSUE THREAD

**Issue by thenickless** [RRZE-Webteam/rrze-elements#88]
Sprungmarken werden aktuell immer mit "collapse-Zahl" ausgegeben. Der Parameter "name" wird offenbar nicht ausgewertet. Dies ist jedoch für zB RRZE-FAQ notwendig, da sich die Elemente stetig verändert können und aktuell nicht auf ein eindeutiges Element verlinkt werden kann.

Beispiel von https://www.wordpress.rrze.fau.de/plugins/fau-und-rrze-plugins/elements/accordion/accordions-verschachteln/  : 

[collapsibles]
[collapse title="Accordionfarben" name="accfarben1"]
Alle Accordionfarben im Überblick
[accordion]
[accordion-item title="Titel Accordion 1" color="phil" name="sprungmarke1"]
Hier der Text
[/accordion-item]
[accordion-item title="Titel Accordion 2" color="med" name="sprungmarke2"]
Hier der Text
[/accordion-item]
[accordion-item title="Titel Accordion 3" color="nat" name="sprungmarke2"]
Hier der Text
[/accordion-item]
[accordion-item title="Titel Accordion 4" color="rw" name="sprungmarke2"]
Hier der Text
[/accordion-item]
[accordion-item title="Titel Accordion 5" color="tf" name="sprungmarke2"]
Hier der Text
[/accordion-item]
[accordion-item title="Titel Accordion 6" color="fau" name="sprungmarke2"]
Hier der Text
[/accordion-item]
[/accordion]
[/collapse]
[collapse title="Zweites Feld" name="accfeld2"]
Inhalt 2. Feld
[/collapse]
[/collapsibles]

**Comment by cassandre** [comment]
Was genau funktioniert daran nicht? Das name-Attribut wird ausgewertet, siehe https://www.wordpress.rrze.fau.de/beispiel-geoeffnetes-accordion-verlinken/#donnerstag. 
Die id (collpase-Zahl) ist nur aus Abwärtskompatibilitätsgründen noch drin.

**Comment by thenickless** [comment]
Bei den Verschachtelten funktioniert die Sprungmarke nicht.

"name" von [accordion-item ..] wird offenbar nicht ausgewertet.

Siehe Beispiel von https://www.wordpress.rrze.fau.de/plugins/fau-und-rrze-plugins/elements/accordion/accordions-verschachteln/ :

[collapsibles]
[collapse title="Accordionfarben" name="accfarben1"]
Alle Accordionfarben im Überblick
[accordion]
[accordion-item title="Titel Accordion 1" color="phil" name="sprungmarke1"]
Hier der Text
[/accordion-item]
[accordion-item title="Titel Accordion 2" color="med" name="sprungmarke2"]
Hier der Text
[/accordion-item]
[accordion-item title="Titel Accordion 3" color="nat" name="sprungmarke2"]
Hier der Text
[/accordion-item]
[accordion-item title="Titel Accordion 4" color="rw" name="sprungmarke2"]
Hier der Text
[/accordion-item]
[accordion-item title="Titel Accordion 5" color="tf" name="sprungmarke2"]
Hier der Text
[/accordion-item]
[accordion-item title="Titel Accordion 6" color="fau" name="sprungmarke2"]
Hier der Text
[/accordion-item]
[/accordion]
[/collapse]
[collapse title="Zweites Feld" name="accfeld2"]
Inhalt 2. Feld
[/collapse]
[/collapsibles]

**Comment by thenickless** [comment]
Die inneren Sprungmarken funktionieren nicht. Siehe oberes Beispiel. Bitte um Korrektur wg https://github.com/RRZE-Webteam/rrze-faq/issues/30 (aktuell benötigt von Daniel de West)

**Comment by cassandre** [comment]
Achso, die _inneren_ Sprungmarken. OK, ich schau mal, was ich machen kann. Wird erledigt.

**Comment by thenickless** [comment]
Es fehlt noch, dass der URL entsprechend in der Adresszeile des Browsers ausgegeben wird, damit die Anwender Links nutzen können, die sich nicht verändern, wenn Elemente hinzukommen oder wegfallen. 

Beim oberen Beispiel:
https://...#sprungmarke2
https://...#accfarben1

Derzeit werden die URLs als https://...#collapse_1 in der Adresszeile des Browsers ausgegeben. 

Verändern sich die Elemente, sind diese Sprungmarken nicht eindeutig.

**Comment by cassandre** [comment]
Das habe ich schon probiert, das funktioniert nicht. In die Adresszeile wird immer die ID des angeklickten Elements ausgegeben. Die permanenten Links kann man trotzdem nutzen, auch wenn man sie nicht sieht. 
Ggf. könte man ein Title-Tag ergänzen in dem man die Sprungmarke auslesen kann.

**Comment by cassandre** [comment]
OK, funktioniert jetzt. Wenn ein name-Attribut gesetzt ist, wird das in die URL geschrieben, ansonsten die ID/href-Attribut.
