### ISSUE TITLE
Absatzklassen-Absätze mit <p> - Icons werden nicht angezeigt

### ISSUE THREAD

**Issue by Albager** [RRZE-Webteam/rrze-elements#89]
Hallo, ist hier schon aufgefallen, dass die Absatzklassen-Icons nicht (mehr) funktionieren, wenn man die Absatzklassen per class-Parameter auf `<p>`-tags anwendet? Vgl. https://www.geographie.nat.fau.de/shortcodes/ - per Shortcode funktioniert es hingegen wie gewohnt.

![image](https://user-images.githubusercontent.com/11389126/79471554-11327c80-8003-11ea-8d9c-48dcc1600c39.png)

Oder mache ich ggf. etwas falsch? Früher hatte es auf diese Weise funktioniert, habe aber jetzt auch länger nicht mehr reingeschaut und kann nicht sagen, seit wann das Problem auftritt.

Beim Nachlesen in der Doku ist mir ferner aufgefallen, dass die Bootstrap-Alerts wie hier beschrieben https://www.beta.wordpress.rrze.fau.de/texte/absatzklassen/ nur zu
funktionieren scheinen, wenn man die Klasse in z. B. ein `<p>`-tag schreibt, und nicht wie in der Doku beschrieben bzw. gezeigt auf ein `<div>` anwendet.
Code:
```
<div class=“alert alert-danger“ role=“alert“> alert-danger div </div>
<div class=“alert alert-danger“ role=“alert“><p>alert-danger div</p></div>
<div><p class="alert alert-danger" role="alert">alert-danger div mit p</p></div>
<p class="alert alert-danger" role="alert"> alert-danger p </p>
```

Ausgabe:
![image](https://user-images.githubusercontent.com/11389126/79472705-75a20b80-8004-11ea-872f-c0c445cb79db.png)

Da ist die beta-Doku m. E. ein bisschen irreführend.

**Comment by cassandre** [comment]
In beiden Fällen (Absatzklassen und Alerts) muss jeweils die allgemeine Klasse ergänzt werden, dann funktioniert es: `class="notice notice-tipp"` bzw. `class="alert alert-danger"`.

An den allgemeinen Klassen hängen die allgemeinen Styles, z.B. der Font für das Notice-Icon und padding etc. für die Alerts.

**Comment by Albager** [comment]
OK, so funktioniert es. Aber die alerts auf ein `div` mit `<div class=“alert alert-danger“ role=“alert“> alert-danger div </div>` funktionieren wie unter https://www.beta.wordpress.rrze.fau.de/texte/absatzklassen/ gezeigt leider trotzdem nicht bzw. im Allgemeinen wäre(n) die Doku(s) bzgl. der korrekten Verwendung von **`<p>`-Absatz-**Klassen noch ausbaufähig.

**Comment by cassandre** [comment]
beta ist eigentlich keine Doku, sondern eine Test-Instanz. Die verbindliche Doku findet sich unter https://www.wordpress.rrze.fau.de/. Dein Beispiel-Code funktioniert auf meiner Test-Instanz eigentlich problemlos. Kann es sein, dass da nur die Anführungszeichen falsch sind?

Grundsätzlich sollte man es eigentlich vermeiden, die Klassen von Hand ohne Shortcode zu verwenden. Zum einen können sich die Plugins gelegentlich ändern, das war ja der Fall bei den Absatzklassen. Zum anderen werden Klassenangaben meines Wissens auch beim Speichern gelöscht, wenn die Seite von einem Benutzer ohne Admin-Rechte bearbeitet wird.

Das p würde ich nicht weiter unterstützen wollen: Ein div ist flexibler, da es sowohl einen als auch mehrere Absätze enthalten kann. Daher: Es gibt keine korrekte Verwendung von p-Absatzklassen mehr. ;-)

**Comment by Albager** [comment]
Okay. Ich verweise auch immer wieder Leute auf die beta, weil dort sehr schöne Beispiele zu sehen sind. Mir war bisher gar nicht klar, dass das "nur" eine Testinstanz ist. Also insofern alles ok, und in der Frage `<p>` vs. `div` bin auch ich bei dir ✌️
